{% set name = "gast" %}
{% set version = "0.5.2" %}
{% set sha256 = "f81fcefa8b982624a31c9e4ec7761325a88a0eba60d36d1da90e47f8fe3c67f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python  >=3.4
    - pip
  run:
    - python  >=3.4

test:
  imports:
    - gast

about:
  home: https://github.com/serge-sans-paille/gast
  license: BSD-3-Clause
  license_family: BSD
  # https://github.com/serge-sans-paille/gast/pull/17
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).

  description: |
    GAST provides a compatibility layer between the AST of various Python 
    versions, as produced by ast.parse from the standard ast module.
  dev_url: https://github.com/serge-sans-paille/gast

extra:
  recipe-maintainers:
    - CurtLH
    - martinRenou
